### ISSUE TITLE
Cashbill | invalid signature generator

### ISSUE THREAD

**Issue by SUGEREK** [WiktorDev/polish-payments-lib#1]
An incorrect signature is generated in the payment generation, I have checked this and the values to generate the signature are not in the correct order as recommended by the documentation.
![image](https://user-images.githubusercontent.com/74995616/192564859-a3f6c545-2d58-45af-8bdf-3e544047d76b.png)

**Comment by WiktorDev** [comment]
Signature is dynamically generated with all arguments given.
![obraz](https://user-images.githubusercontent.com/70075488/192567413-8a927c5b-f944-4367-adab-6c8ff950fde7.png)

Overall, I recommend using the newer version: https://github.com/WiktorDev/node-payments-lib2.0

**Comment by SUGEREK** [comment]
I wrote it in the wrong repo, I meant the v2 version.
